address = "127.0.0.1:7799"
failure_ttl = 60
failure_quorum = 1
migration_limit = 2

recover_from_meta_file = true
meta_filename = "metadata"
# Refresh meta file on each update
auto_update_meta_file = true
# Periodically update meta file.
# This is in seconds.
# Use zero to disable it.
update_meta_file_interval = 10

# The HTTP API address of other memory brokers.
replica_addresses = []
# replica_addresses = ["192.168.0.123:7799", "192.168.0.123:8899"]
# replica_addresses = "192.168.0.123:7799,192.168.0.123:8899"

# Periodically synchronize metadata to replicas.
# This is in seconds.
# Use zero to disable it.
sync_meta_interval = 10

# Set it to `true` for kubernetes StatefulSet
# to disable the chunk allocation algorithm
# and only use the index of server proxy to allocate chunks.
# If this is true，
# (1) when adding proxies, the "index" field is required and should be the index of the StatefulSet index.
# (2) failover will only change the role and will not replace proxy.
# (3) the whole undermoon cluster can only create one Redis cluster.
enable_ordered_proxy = false

storage_type = "memory"

# Use the following config to enable external http storage.
#
# undermoon_name = "my_undermoon_name"
# storage_type = "http"
# http_storage_address = "localhost:9999"
# refresh_interval = 5

debug = false
